version: '3'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-network

  payingguest-db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=payingguestdb
      - MYSQL_USER=payingguestuser
      - MYSQL_PASSWORD=payingguestpassword
    volumes:
      - /var/lib/mysql_payingguest_data:/var/lib/mysql
    networks:
      - app-network

  payingguest-application:
    image: payingguest-application:latest
    restart: always
    depends_on:
      - kafka
      - user-db
    ports:
      - 8080:8080
    volumes:
      - /var/payingguest/log:/var/log
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://payingguest-db:3306/payingguestdb
      SPRING_DATASOURCE_USERNAME: payingguestuser
      SPRING_DATASOURCE_PASSWORD: payingguestpassword
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://localhost:8761/eureka
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
      # Authentication token validity is 10 mins
      JWT_VALIDITY_TOKEN: 600000 
    networks:
      - app-network
      - kafka-network

networks:
  kafka-network:
    driver: bridge
  app-network:
    driver: bridge
